<?xml version="1.0" encoding="utf-8"?><Database Name="KutuphaneDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MEHMET\SQLEXPRESS;Initial Catalog=KutuphaneDatabase;Integrated Security=True" SettingsObjectName="kutuphane.Properties.Settings" SettingsPropertyName="KutuphaneDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.kategori" Member="kategori">
    <Type Name="kategori">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="kategori_kitap" Member="kitap" ThisKey="id" OtherKey="kategoriID" Type="kitap" />
    </Type>
  </Table>
  <Table Name="dbo.kitap" Member="kitap">
    <Type Name="kitap">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="isbn" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="yazarAdi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kategoriID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="yayıneviID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="kitap_yerbilgisi" Member="yerbilgisi" ThisKey="id" OtherKey="kitapID" Type="yerbilgisi" />
      <Association Name="kitap_odunc" Member="odunc" ThisKey="id" OtherKey="kitapID" Type="odunc" />
      <Association Name="kategori_kitap" Member="kategori" ThisKey="kategoriID" OtherKey="id" Type="kategori" IsForeignKey="true" />
      <Association Name="yayinevi_kitap" Member="yayinevi" ThisKey="yayıneviID" OtherKey="id" Type="yayinevi" IsForeignKey="true" />
      <Association Name="yazar_kitap" Member="yazar" ThisKey="yazarAdi" OtherKey="ad" Type="yazar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.kutuphane" Member="kutuphane">
    <Type Name="kutuphane">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="adres" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="kutuphane_yerbilgisi" Member="yerbilgisi" ThisKey="id" OtherKey="kutuphaneID" Type="yerbilgisi" />
      <Association Name="kutuphane_kayıt" Member="kayıt" ThisKey="id" OtherKey="kutuphaneID" Type="kayıt" />
      <Association Name="kutuphane_odunc" Member="odunc" ThisKey="id" OtherKey="kutuphaneID" Type="odunc" />
    </Type>
  </Table>
  <Table Name="dbo.uye" Member="uye">
    <Type Name="uye">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soyad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sifre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="uye_kayıt" Member="kayıt" ThisKey="id" OtherKey="uyeID" Type="kayıt" />
      <Association Name="uye_odunc" Member="odunc" ThisKey="id" OtherKey="uyeID" Type="odunc" />
    </Type>
  </Table>
  <Table Name="dbo.yayinevi" Member="yayinevi">
    <Type Name="yayinevi">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="adres" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Association Name="yayinevi_kitap" Member="kitap" ThisKey="id" OtherKey="yayıneviID" Type="kitap" />
    </Type>
  </Table>
  <Table Name="dbo.yazar" Member="yazar">
    <Type Name="yazar">
      <Column Name="ad" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="adres" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Association Name="yazar_kitap" Member="kitap" ThisKey="ad" OtherKey="yazarAdi" Type="kitap" />
    </Type>
  </Table>
  <Table Name="dbo.yerbilgisi" Member="yerbilgisi">
    <Type Name="yerbilgisi">
      <Column Name="kitapID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kutuphaneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="yerNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="durum" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="kitap_yerbilgisi" Member="kitap" ThisKey="kitapID" OtherKey="id" Type="kitap" IsForeignKey="true" />
      <Association Name="kutuphane_yerbilgisi" Member="kutuphane" ThisKey="kutuphaneID" OtherKey="id" Type="kutuphane" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.admin" Member="admin">
    <Type Name="admin">
      <Column Name="ad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kutuphaneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sifre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="adres" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kayıt" Member="kayıt">
    <Type Name="kayıt">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kutuphaneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="uyeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kayit_tarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="kutuphane_kayıt" Member="kutuphane" ThisKey="kutuphaneID" OtherKey="id" Type="kutuphane" IsForeignKey="true" />
      <Association Name="uye_kayıt" Member="uye" ThisKey="uyeID" OtherKey="id" Type="uye" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.odunc" Member="odunc">
    <Type Name="odunc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="kutuphaneID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uyeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kitapID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="odunc_alma_tarihi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="son_teslim_tarihi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="kitap_odunc" Member="kitap" ThisKey="kitapID" OtherKey="id" Type="kitap" IsForeignKey="true" />
      <Association Name="kutuphane_odunc" Member="kutuphane" ThisKey="kutuphaneID" OtherKey="id" Type="kutuphane" IsForeignKey="true" />
      <Association Name="uye_odunc" Member="uye" ThisKey="uyeID" OtherKey="id" Type="uye" IsForeignKey="true" />
    </Type>
  </Table>
</Database>