#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KutuphaneDatabase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkategori(kategori instance);
    partial void Updatekategori(kategori instance);
    partial void Deletekategori(kategori instance);
    partial void Insertkitap(kitap instance);
    partial void Updatekitap(kitap instance);
    partial void Deletekitap(kitap instance);
    partial void Insertkutuphane(kutuphane instance);
    partial void Updatekutuphane(kutuphane instance);
    partial void Deletekutuphane(kutuphane instance);
    partial void Insertuye(uye instance);
    partial void Updateuye(uye instance);
    partial void Deleteuye(uye instance);
    partial void Insertyayinevi(yayinevi instance);
    partial void Updateyayinevi(yayinevi instance);
    partial void Deleteyayinevi(yayinevi instance);
    partial void Insertyazar(yazar instance);
    partial void Updateyazar(yazar instance);
    partial void Deleteyazar(yazar instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::kutuphane.Properties.Settings.Default.KutuphaneDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kategori> kategori
		{
			get
			{
				return this.GetTable<kategori>();
			}
		}
		
		public System.Data.Linq.Table<kayıt> kayıt
		{
			get
			{
				return this.GetTable<kayıt>();
			}
		}
		
		public System.Data.Linq.Table<kitap> kitap
		{
			get
			{
				return this.GetTable<kitap>();
			}
		}
		
		public System.Data.Linq.Table<kutuphane> kutuphane
		{
			get
			{
				return this.GetTable<kutuphane>();
			}
		}
		
		public System.Data.Linq.Table<odunc> odunc
		{
			get
			{
				return this.GetTable<odunc>();
			}
		}
		
		public System.Data.Linq.Table<uye> uye
		{
			get
			{
				return this.GetTable<uye>();
			}
		}
		
		public System.Data.Linq.Table<yayinevi> yayinevi
		{
			get
			{
				return this.GetTable<yayinevi>();
			}
		}
		
		public System.Data.Linq.Table<yazar> yazar
		{
			get
			{
				return this.GetTable<yazar>();
			}
		}
		
		public System.Data.Linq.Table<yerbilgisi> yerbilgisi
		{
			get
			{
				return this.GetTable<yerbilgisi>();
			}
		}
		
		public System.Data.Linq.Table<admin> admin
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategori")]
	public partial class kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
		private EntitySet<kitap> _kitap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    #endregion
		
		public kategori()
		{
			this._kitap = new EntitySet<kitap>(new Action<kitap>(this.attach_kitap), new Action<kitap>(this.detach_kitap));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategori_kitap", Storage="_kitap", ThisKey="id", OtherKey="kategoriID")]
		public EntitySet<kitap> kitap
		{
			get
			{
				return this._kitap;
			}
			set
			{
				this._kitap.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kitap(kitap entity)
		{
			this.SendPropertyChanging();
			entity.kategori = this;
		}
		
		private void detach_kitap(kitap entity)
		{
			this.SendPropertyChanging();
			entity.kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kayıt")]
	public partial class kayıt
	{
		
		private int _kutuphaneID;
		
		private int _uyeID;
		
		private System.Nullable<System.DateTime> _kayit_tarihi;
		
		public kayıt()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kutuphaneID", DbType="Int NOT NULL")]
		public int kutuphaneID
		{
			get
			{
				return this._kutuphaneID;
			}
			set
			{
				if ((this._kutuphaneID != value))
				{
					this._kutuphaneID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeID", DbType="Int NOT NULL")]
		public int uyeID
		{
			get
			{
				return this._uyeID;
			}
			set
			{
				if ((this._uyeID != value))
				{
					this._uyeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_tarihi", DbType="Date")]
		public System.Nullable<System.DateTime> kayit_tarihi
		{
			get
			{
				return this._kayit_tarihi;
			}
			set
			{
				if ((this._kayit_tarihi != value))
				{
					this._kayit_tarihi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kitap")]
	public partial class kitap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _isbn;
		
		private string _ad;
		
		private string _yazarAdi;
		
		private System.Nullable<int> _kategoriID;
		
		private System.Nullable<int> _yayıneviID;
		
		private EntityRef<kategori> _kategori;
		
		private EntityRef<yayinevi> _yayinevi;
		
		private EntityRef<yazar> _yazar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnisbnChanging(string value);
    partial void OnisbnChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnyazarAdiChanging(string value);
    partial void OnyazarAdiChanged();
    partial void OnkategoriIDChanging(System.Nullable<int> value);
    partial void OnkategoriIDChanged();
    partial void OnyayıneviIDChanging(System.Nullable<int> value);
    partial void OnyayıneviIDChanged();
    #endregion
		
		public kitap()
		{
			this._kategori = default(EntityRef<kategori>);
			this._yayinevi = default(EntityRef<yayinevi>);
			this._yazar = default(EntityRef<yazar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbn", DbType="NChar(10)")]
		public string isbn
		{
			get
			{
				return this._isbn;
			}
			set
			{
				if ((this._isbn != value))
				{
					this.OnisbnChanging(value);
					this.SendPropertyChanging();
					this._isbn = value;
					this.SendPropertyChanged("isbn");
					this.OnisbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50)")]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yazarAdi", DbType="NVarChar(50)")]
		public string yazarAdi
		{
			get
			{
				return this._yazarAdi;
			}
			set
			{
				if ((this._yazarAdi != value))
				{
					if (this._yazar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnyazarAdiChanging(value);
					this.SendPropertyChanging();
					this._yazarAdi = value;
					this.SendPropertyChanged("yazarAdi");
					this.OnyazarAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategoriID", DbType="Int")]
		public System.Nullable<int> kategoriID
		{
			get
			{
				return this._kategoriID;
			}
			set
			{
				if ((this._kategoriID != value))
				{
					if (this._kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkategoriIDChanging(value);
					this.SendPropertyChanging();
					this._kategoriID = value;
					this.SendPropertyChanged("kategoriID");
					this.OnkategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yayıneviID", DbType="Int")]
		public System.Nullable<int> yayıneviID
		{
			get
			{
				return this._yayıneviID;
			}
			set
			{
				if ((this._yayıneviID != value))
				{
					if (this._yayinevi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnyayıneviIDChanging(value);
					this.SendPropertyChanging();
					this._yayıneviID = value;
					this.SendPropertyChanged("yayıneviID");
					this.OnyayıneviIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategori_kitap", Storage="_kategori", ThisKey="kategoriID", OtherKey="id", IsForeignKey=true)]
		public kategori kategori
		{
			get
			{
				return this._kategori.Entity;
			}
			set
			{
				kategori previousValue = this._kategori.Entity;
				if (((previousValue != value) 
							|| (this._kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategori.Entity = null;
						previousValue.kitap.Remove(this);
					}
					this._kategori.Entity = value;
					if ((value != null))
					{
						value.kitap.Add(this);
						this._kategoriID = value.id;
					}
					else
					{
						this._kategoriID = default(Nullable<int>);
					}
					this.SendPropertyChanged("kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yayinevi_kitap", Storage="_yayinevi", ThisKey="yayıneviID", OtherKey="id", IsForeignKey=true)]
		public yayinevi yayinevi
		{
			get
			{
				return this._yayinevi.Entity;
			}
			set
			{
				yayinevi previousValue = this._yayinevi.Entity;
				if (((previousValue != value) 
							|| (this._yayinevi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yayinevi.Entity = null;
						previousValue.kitap.Remove(this);
					}
					this._yayinevi.Entity = value;
					if ((value != null))
					{
						value.kitap.Add(this);
						this._yayıneviID = value.id;
					}
					else
					{
						this._yayıneviID = default(Nullable<int>);
					}
					this.SendPropertyChanged("yayinevi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yazar_kitap", Storage="_yazar", ThisKey="yazarAdi", OtherKey="ad", IsForeignKey=true)]
		public yazar yazar
		{
			get
			{
				return this._yazar.Entity;
			}
			set
			{
				yazar previousValue = this._yazar.Entity;
				if (((previousValue != value) 
							|| (this._yazar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yazar.Entity = null;
						previousValue.kitap.Remove(this);
					}
					this._yazar.Entity = value;
					if ((value != null))
					{
						value.kitap.Add(this);
						this._yazarAdi = value.ad;
					}
					else
					{
						this._yazarAdi = default(string);
					}
					this.SendPropertyChanged("yazar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kutuphane")]
	public partial class kutuphane : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
		private string _adres;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    #endregion
		
		public kutuphane()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(50)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.odunc")]
	public partial class odunc
	{
		
		private int _kutuphaneID;
		
		private int _uyeID;
		
		private int _kitapID;
		
		private System.DateTime _odunc_alma_tarihi;
		
		private System.DateTime _son_teslim_tarihi;
		
		public odunc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kutuphaneID", DbType="Int NOT NULL")]
		public int kutuphaneID
		{
			get
			{
				return this._kutuphaneID;
			}
			set
			{
				if ((this._kutuphaneID != value))
				{
					this._kutuphaneID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeID", DbType="Int NOT NULL")]
		public int uyeID
		{
			get
			{
				return this._uyeID;
			}
			set
			{
				if ((this._uyeID != value))
				{
					this._uyeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kitapID", DbType="Int NOT NULL")]
		public int kitapID
		{
			get
			{
				return this._kitapID;
			}
			set
			{
				if ((this._kitapID != value))
				{
					this._kitapID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odunc_alma_tarihi", DbType="Date NOT NULL")]
		public System.DateTime odunc_alma_tarihi
		{
			get
			{
				return this._odunc_alma_tarihi;
			}
			set
			{
				if ((this._odunc_alma_tarihi != value))
				{
					this._odunc_alma_tarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_son_teslim_tarihi", DbType="Date NOT NULL")]
		public System.DateTime son_teslim_tarihi
		{
			get
			{
				return this._son_teslim_tarihi;
			}
			set
			{
				if ((this._son_teslim_tarihi != value))
				{
					this._son_teslim_tarihi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uye")]
	public partial class uye : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _tc;
		
		private string _ad;
		
		private string _soyad;
		
		private string _email;
		
		private string _sifre;
		
		private string _tel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntcChanging(int value);
    partial void OntcChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    #endregion
		
		public uye()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc", DbType="Int NOT NULL")]
		public int tc
		{
			get
			{
				return this._tc;
			}
			set
			{
				if ((this._tc != value))
				{
					this.OntcChanging(value);
					this.SendPropertyChanging();
					this._tc = value;
					this.SendPropertyChanged("tc");
					this.OntcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string soyad
		{
			get
			{
				return this._soyad;
			}
			set
			{
				if ((this._soyad != value))
				{
					this.OnsoyadChanging(value);
					this.SendPropertyChanging();
					this._soyad = value;
					this.SendPropertyChanged("soyad");
					this.OnsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(50)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yayinevi")]
	public partial class yayinevi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ad;
		
		private string _adres;
		
		private string _tel;
		
		private EntitySet<kitap> _kitap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    #endregion
		
		public yayinevi()
		{
			this._kitap = new EntitySet<kitap>(new Action<kitap>(this.attach_kitap), new Action<kitap>(this.detach_kitap));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(50)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(12)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yayinevi_kitap", Storage="_kitap", ThisKey="id", OtherKey="yayıneviID")]
		public EntitySet<kitap> kitap
		{
			get
			{
				return this._kitap;
			}
			set
			{
				this._kitap.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kitap(kitap entity)
		{
			this.SendPropertyChanging();
			entity.yayinevi = this;
		}
		
		private void detach_kitap(kitap entity)
		{
			this.SendPropertyChanging();
			entity.yayinevi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yazar")]
	public partial class yazar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ad;
		
		private string _adres;
		
		private string _tel;
		
		private EntitySet<kitap> _kitap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    #endregion
		
		public yazar()
		{
			this._kitap = new EntitySet<kitap>(new Action<kitap>(this.attach_kitap), new Action<kitap>(this.detach_kitap));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(50)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(12)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yazar_kitap", Storage="_kitap", ThisKey="ad", OtherKey="yazarAdi")]
		public EntitySet<kitap> kitap
		{
			get
			{
				return this._kitap;
			}
			set
			{
				this._kitap.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kitap(kitap entity)
		{
			this.SendPropertyChanging();
			entity.yazar = this;
		}
		
		private void detach_kitap(kitap entity)
		{
			this.SendPropertyChanging();
			entity.yazar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yerbilgisi")]
	public partial class yerbilgisi
	{
		
		private int _kitapID;
		
		private int _kutuphaneID;
		
		private string _yerNo;
		
		private string _durum;
		
		public yerbilgisi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kitapID", DbType="Int NOT NULL")]
		public int kitapID
		{
			get
			{
				return this._kitapID;
			}
			set
			{
				if ((this._kitapID != value))
				{
					this._kitapID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kutuphaneID", DbType="Int NOT NULL")]
		public int kutuphaneID
		{
			get
			{
				return this._kutuphaneID;
			}
			set
			{
				if ((this._kutuphaneID != value))
				{
					this._kutuphaneID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yerNo", DbType="NVarChar(50)")]
		public string yerNo
		{
			get
			{
				return this._yerNo;
			}
			set
			{
				if ((this._yerNo != value))
				{
					this._yerNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum", DbType="NVarChar(10)")]
		public string durum
		{
			get
			{
				return this._durum;
			}
			set
			{
				if ((this._durum != value))
				{
					this._durum = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin
	{
		
		private string _ad;
		
		private string _tc;
		
		private int _id;
		
		private int _kutuphaneID;
		
		private string _sifre;
		
		private string _adres;
		
		private string _tel;
		
		public admin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this._ad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tc
		{
			get
			{
				return this._tc;
			}
			set
			{
				if ((this._tc != value))
				{
					this._tc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kutuphaneID", DbType="Int NOT NULL")]
		public int kutuphaneID
		{
			get
			{
				return this._kutuphaneID;
			}
			set
			{
				if ((this._kutuphaneID != value))
				{
					this._kutuphaneID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this._sifre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(50)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this._adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(50)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this._tel = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
